# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3af2f3ed7ed9714e15777d379cbcad151858ebe7dce5ea57623ef19bc30fdb6892fc94ab6131f137a54cc1a744d6105436ee1c9ca8f0168ab9dfcb4301715591

test:
  secret_key_base: b343d85c78828481bee34c8e9a78f15104ad812f7cf301804a272a6d4f9b0f545d5ca25e70e043a8773cd483be7714eda4cc2b714911e3891fd98f31be8b328b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
